-- Supabase SQL Editor で1回実行してください。
-- music_packs テーブルと zip-packs bucket を作成します。

create table if not exists public.music_packs (
  id bigint generated by default as identity primary key,
  title text not null default '',
  tags text not null default '',
  youtube_url text not null default '',
  zip_url text not null default '',
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.music_packs enable row level security;

drop policy if exists "Public can view published music packs" on public.music_packs;
create policy "Public can view published music packs"
on public.music_packs
for select
to anon, authenticated
using (is_published = true or auth.role() = 'authenticated');

drop policy if exists "Authenticated users can insert music packs" on public.music_packs;
create policy "Authenticated users can insert music packs"
on public.music_packs
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update music packs" on public.music_packs;
create policy "Authenticated users can update music packs"
on public.music_packs
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete music packs" on public.music_packs;
create policy "Authenticated users can delete music packs"
on public.music_packs
for delete
to authenticated
using (true);

insert into storage.buckets (id, name, public)
values ('zip-packs', 'zip-packs', true)
on conflict (id) do update set public = true;

drop policy if exists "Authenticated users can upload zip packs" on storage.objects;
create policy "Authenticated users can upload zip packs"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'zip-packs');

drop policy if exists "Authenticated users can update zip packs" on storage.objects;
create policy "Authenticated users can update zip packs"
on storage.objects
for update
to authenticated
using (bucket_id = 'zip-packs')
with check (bucket_id = 'zip-packs');

drop policy if exists "Authenticated users can delete zip packs" on storage.objects;
create policy "Authenticated users can delete zip packs"
on storage.objects
for delete
to authenticated
using (bucket_id = 'zip-packs');
